In [2]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm
from glob import glob

In [14]:
base_path = os.path.join('cricket_pred', 't20s')
filenames = glob(os.path.join(base_path, '*.yaml')) # Change to *.json if needed

all_dfs = []
counter = 1

print(f"Found {len(filenames)} files. Starting processing...")

# 2. Process files with error handling
for file_path in tqdm(filenames[-1000:-900]):
    try:
        with open(file_path, 'r') as f:
            data = safe_load(f)
            
            # Validation: Fixes the NotImplementedError
            if data is None or not isinstance(data, (dict, list)):
                continue
                
            # Flatten the data
            df = pd.json_normalize(data)
            
            # Add metadata
            df['match_id'] = counter
            df['source_file'] = os.path.basename(file_path)
            
            all_dfs.append(df)
            counter += 1
            
    except Exception as e:
        print(f"Error processing {file_path}: {e}")

# 3. Combine everything
if all_dfs:
    final_df = pd.concat(all_dfs, ignore_index=True)
    print("Success! Combined DataFrame shape:", final_df.shape)
else:
    print("No valid data found.")

# Display result
final_df.tail()

Found 4801 files. Starting processing...

100%|██████████| 100/100 [00:24<00:00,  4.10it/s]

Success! Combined DataFrame shape: (100, 687)

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,info.match_type_number,...,info.registry.people.Mustafa Omer,info.registry.people.Noman Amjad,info.registry.people.Qamar Mushtaque,info.registry.people.R Mangal,info.registry.people.Usman Afzal,info.registry.people.Vinay Ravi,info.registry.people.Vishal Sharma,info.registry.people.Walid Ghauri,info.registry.people.Zaheer Zahiri,info.registry.people.Zain Ahmad
95,"[{'1st innings': {'team': 'Austria', 'deliveri...",0.92,2025-07-26,1,6,Szodliget,[2025-07-26],male,T20,3377,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,"[{'1st innings': {'team': 'Hungary', 'deliveri...",0.92,2025-07-28,1,6,Szodliget,[2025-07-27],male,T20,3379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,"[{'1st innings': {'team': 'Austria', 'deliveri...",0.92,2025-07-28,1,6,Szodliget,[2025-07-27],male,T20,3381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,"[{'1st innings': {'team': 'Sweden', 'deliverie...",0.92,2025-08-16,1,6,Stockholm,[2025-08-08],male,T20,3399,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,"[{'1st innings': {'team': 'Norway', 'deliverie...",0.92,2025-08-16,1,6,Stockholm,[2025-08-08],male,T20,3397,...,3bd52be1,c079c66a,fc362c5d,5360c9be,63aa66b9,9c181b99,b9d8abd3,331e137f,62f6d8ce,ea2c0aff

In [15]:
backup = final_df.copy()

In [17]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.eliminator',
    'info.outcome.result',
    'info.outcome.method',
    'info.match_type_number',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

In [26]:
final_df = backup

In [27]:
final_df['info.gender'].value_counts()

info.gender
male      75
female    25
Name: count, dtype: int64

In [28]:
final_df = final_df[final_df['info.gender']=='male']
final_df = final_df.drop(columns=['info.gender'])
final_df

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.match_type,info.match_type_number,info.outcome.result,...,info.registry.people.Mustafa Omer,info.registry.people.Noman Amjad,info.registry.people.Qamar Mushtaque,info.registry.people.R Mangal,info.registry.people.Usman Afzal,info.registry.people.Vinay Ravi,info.registry.people.Vishal Sharma,info.registry.people.Walid Ghauri,info.registry.people.Zaheer Zahiri,info.registry.people.Zain Ahmad
0,"[{'1st innings': {'team': 'West Indies', 'deli...",0.92,2025-11-10,1,6,Nelson,[2025-11-10],T20,3568,no result,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'West Indies', 'deli...",0.92,2025-11-17,1,6,Dunedin,[2025-11-13],T20,3574,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.92,2025-07-24,1,6,Dhaka,[2025-07-20],T20,3338,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.92,2025-07-24,1,6,Dhaka,[2025-07-22],T20,3349,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.92,2025-07-25,1,6,Dhaka,[2025-07-24],T20,3361,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"[{'1st innings': {'team': 'Austria', 'deliveri...",0.92,2025-07-26,1,6,Szodliget,[2025-07-26],T20,3377,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,"[{'1st innings': {'team': 'Hungary', 'deliveri...",0.92,2025-07-28,1,6,Szodliget,[2025-07-27],T20,3379,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,"[{'1st innings': {'team': 'Austria', 'deliveri...",0.92,2025-07-28,1,6,Szodliget,[2025-07-27],T20,3381,no result,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,"[{'1st innings': {'team': 'Sweden', 'deliverie...",0.92,2025-08-16,1,6,Stockholm,[2025-08-08],T20,3399,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,"[{'1st innings': {'team': 'Norway', 'deliverie...",0.92,2025-08-16,1,6,Stockholm,[2025-08-08],T20,3397,NaN,...,3bd52be1,c079c66a,fc362c5d,5360c9be,63aa66b9,9c181b99,b9d8abd3,331e137f,62f6d8ce,ea2c0aff

In [29]:
final_df['info.match_type'].value_counts()

info.match_type
T20    75
Name: count, dtype: int64

In [30]:
final_df['info.overs'].value_counts()

info.overs
20    75
Name: count, dtype: int64

In [32]:
# if all would not have been 20 then
# final_df = final_df[final_df['info.overs'] == 20]
# final_df = final_df.drop(columns=['info.overs','info.match_type'],inplace=True)
# final_df

In [33]:
import pickle
pickle.dump(final_df,open('dataset_level1.pkl','wb'))

In [35]:
matches = pickle.load(open('dataset_level1.pkl','rb'))
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'non_striker': 'A Athanaze',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {0.2: {'non_striker': 'A Athanaze',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {0.3: {'non_striker': 'A Athanaze',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AA Jangoo'}},
 {0.4: {'non_striker': 'AA Jangoo',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'A Athanaze'}},
 {0.5: {'non_striker': 'A Athanaze',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {0.6: {'non_striker': 'A Athanaze',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AA Jangoo'}},
 {1.1: {'non_striker': 'A Athanaze',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {1.2: {'non_striker': 'A Athanaze',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {1.3: {'non_striker': 'A Athanaze',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AA Jangoo'}},
 {1.4: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {1.5: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {1.6: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'A Athanaze'}},
 {2.1: {'non_striker': 'AA Jangoo',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {2.2: {'non_striker': 'AA Jangoo',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'A Athanaze'}},
 {2.3: {'non_striker': 'AA Jangoo',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {2.4: {'non_striker': 'AA Jangoo',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'A Athanaze'}},
 {2.5: {'non_striker': 'AA Jangoo',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {2.6: {'non_striker': 'AA Jangoo',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'A Athanaze'}},
 {2.7: {'non_striker': 'AA Jangoo',
   'bowler': 'KA Jamieson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'A Athanaze'}},
 {3.1: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {3.2: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {3.3: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {3.4: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'A Athanaze'}},
 {3.5: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'A Athanaze'}},
 {3.6: {'non_striker': 'AA Jangoo',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'A Athanaze'}},
 {3.7: {'non_striker': 'A Athanaze',
   'bowler': 'JA Duffy',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {4.1: {'non_striker': 'AA Jangoo',
   'bowler': 'MG Bracewell',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'A Athanaze'}},
 {4.2: {'non_striker': 'A Athanaze',
   'bowler': 'MG Bracewell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {4.3: {'non_striker': 'A Athanaze',
   'bowler': 'MG Bracewell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {4.4: {'non_striker': 'A Athanaze',
   'bowler': 'MG Bracewell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {4.5: {'non_striker': 'A Athanaze',
   'bowler': 'MG Bracewell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {4.6: {'non_striker': 'A Athanaze',
   'bowler': 'MG Bracewell',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'AA Jangoo'}},
 {5.1: {'non_striker': 'AA Jangoo',
   'bowler': 'JDS Neesham',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze'}},
 {5.2: {'non_striker': 'AA Jangoo',
   'bowler': 'JDS Neesham',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'A Athanaze',
   'wicket': {'player_out': 'A Athanaze',
    'fielders': ['DJ Mitchell'],
    'kind': 'caught'}}},
 {5.3: {'non_striker': 'AA Jangoo',
   'bowler': 'JDS Neesham',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SD Hope'}},
 {5.4: {'non_striker': 'SD Hope',
   'bowler': 'JDS Neesham',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {5.5: {'non_striker': 'SD Hope',
   'bowler': 'JDS Neesham',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AA Jangoo'}},
 {5.6: {'non_striker': 'SD Hope',
   'bowler': 'JDS Neesham',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'AA Jangoo'}},
 {6.1: {'non_striker': 'AA Jangoo',
   'bowler': 'IS Sodhi',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SD Hope'}},
 {6.2: {'non_striker': 'SD Hope',
   'bowler': 'IS Sodhi',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AA Jangoo'}},
 {6.3: {'non_striker': 'AA Jangoo',
   'bowler': 'IS Sodhi',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SD Hope'}}]

In [46]:
count = 1
all_deliveries = []   # 🔥 store dfs here instead of appending

for index, row in matches.iterrows():
    
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count += 1
        continue
    
    count += 1
    
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    
    try:
        deliveries = row['innings'][0]['1st innings']['deliveries']
        team_name = row['innings'][0]['1st innings']['team']
        
        for ball in deliveries:
            for key in ball.keys():
                match_id.append(count)
                batting_team.append(team_name)
                teams.append(row['info.teams'])
                ball_of_match.append(key)
                batsman.append(ball[key]['batsman'])
                bowler.append(ball[key]['bowler'])
                runs.append(ball[key]['runs']['total'])
                city.append(row.get('info.city', 'Unknown'))
                venue.append(row.get('info.venue', 'Unknown'))
                
                # safer wicket handling
                player_of_dismissed.append(
                    ball[key].get('wicket', {}).get('player_out', '0')
                )
    
    except Exception:
        continue
    
    loop_df = pd.DataFrame({
        'match_id': match_id,
        'teams': teams,
        'batting_team': batting_team,
        'ball': ball_of_match,
        'batsman': batsman,
        'bowler': bowler,
        'runs': runs,
        'player_dismissed': player_of_dismissed,
        'city': city,
        'venue': venue
    })
    
    all_deliveries.append(loop_df)

# 🔥 ONE concat at end
delivery_df = pd.concat(all_deliveries, ignore_index=True)

delivery_df.head()

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[West Indies, New Zealand]",West Indies,0.1,AA Jangoo,KA Jamieson,0,0,Nelson,"Saxton Oval, Nelson"
1,2,"[West Indies, New Zealand]",West Indies,0.2,AA Jangoo,KA Jamieson,0,0,Nelson,"Saxton Oval, Nelson"
2,2,"[West Indies, New Zealand]",West Indies,0.3,AA Jangoo,KA Jamieson,1,0,Nelson,"Saxton Oval, Nelson"
3,2,"[West Indies, New Zealand]",West Indies,0.4,A Athanaze,KA Jamieson,1,0,Nelson,"Saxton Oval, Nelson"
4,2,"[West Indies, New Zealand]",West Indies,0.5,AA Jangoo,KA Jamieson,0,0,Nelson,"Saxton Oval, Nelson"

In [47]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [48]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [50]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[West Indies, New Zealand]",West Indies,0.1,AA Jangoo,KA Jamieson,0,0,Nelson,"Saxton Oval, Nelson",New Zealand
1,2,"[West Indies, New Zealand]",West Indies,0.2,AA Jangoo,KA Jamieson,0,0,Nelson,"Saxton Oval, Nelson",New Zealand
2,2,"[West Indies, New Zealand]",West Indies,0.3,AA Jangoo,KA Jamieson,1,0,Nelson,"Saxton Oval, Nelson",New Zealand
3,2,"[West Indies, New Zealand]",West Indies,0.4,A Athanaze,KA Jamieson,1,0,Nelson,"Saxton Oval, Nelson",New Zealand
4,2,"[West Indies, New Zealand]",West Indies,0.5,AA Jangoo,KA Jamieson,0,0,Nelson,"Saxton Oval, Nelson",New Zealand
...,...,...,...,...,...,...,...,...,...,...,...
8879,75,"[Sweden, Austria]",Sweden,18.6,Abdul Naser Baluch,Karanbir Singh,1,0,Stockholm,"Botkyrka Cricket Center, Stockholm",Austria
8880,75,"[Sweden, Austria]",Sweden,19.1,Abdul Naser Baluch,Ziaurahman Shinwari,0,0,Stockholm,"Botkyrka Cricket Center, Stockholm",Austria
8881,75,"[Sweden, Austria]",Sweden,19.2,Abdul Naser Baluch,Ziaurahman Shinwari,6,0,Stockholm,"Botkyrka Cricket Center, Stockholm",Austria
8882,75,"[Sweden, Austria]",Sweden,19.3,Abdul Naser Baluch,Ziaurahman Shinwari,0,0,Stockholm,"Botkyrka Cricket Center, Stockholm",Austria
8883,75,"[Sweden, Austria]",Sweden,19.4,Abdul Naser Baluch,Ziaurahman Shinwari,0,Abdul Naser Baluch,Stockholm,"Botkyrka Cricket Center, Stockholm",Austria

In [51]:
delivery_df.drop(columns=['teams'],inplace=True)

In [120]:
delivery_df['batting_team'].unique()

array(['West Indies', 'Pakistan', 'Bangladesh', 'Zimbabwe', 'Sri Lanka',
       'Bahrain', 'Malawi', 'Tanzania', 'Germany', 'Hong Kong',
       'Singapore', 'Samoa', 'Malaysia', 'Uganda', 'Kenya',
       'United Arab Emirates', 'Nigeria', 'Qatar', 'Saudi Arabia',
       'Finland', 'Estonia', 'Switzerland', 'Rwanda', 'Romania',
       'Hungary', 'Austria', 'Sweden'], dtype=object)

In [121]:
delivery_df['bowling_team'].unique()

array(['New Zealand', 'Bangladesh', 'Pakistan', 'Sri Lanka', 'Zimbabwe',
       'Tanzania', 'Germany', 'Bahrain', 'Malawi', 'Malaysia', 'Samoa',
       'Singapore', 'Hong Kong', 'Kenya', 'United Arab Emirates',
       'Nigeria', 'Uganda', 'Saudi Arabia', 'Qatar', 'Estonia', 'Finland',
       'Rwanda', 'Austria', 'Romania', 'Luxembourg'], dtype=object)

In [54]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,West Indies,New Zealand,0.1,0,0,Nelson,"Saxton Oval, Nelson"
1,2,West Indies,New Zealand,0.2,0,0,Nelson,"Saxton Oval, Nelson"
2,2,West Indies,New Zealand,0.3,1,0,Nelson,"Saxton Oval, Nelson"
3,2,West Indies,New Zealand,0.4,1,0,Nelson,"Saxton Oval, Nelson"
4,2,West Indies,New Zealand,0.5,0,0,Nelson,"Saxton Oval, Nelson"
...,...,...,...,...,...,...,...,...
8879,75,Sweden,Austria,18.6,1,0,Stockholm,"Botkyrka Cricket Center, Stockholm"
8880,75,Sweden,Austria,19.1,0,0,Stockholm,"Botkyrka Cricket Center, Stockholm"
8881,75,Sweden,Austria,19.2,6,0,Stockholm,"Botkyrka Cricket Center, Stockholm"
8882,75,Sweden,Austria,19.3,0,0,Stockholm,"Botkyrka Cricket Center, Stockholm"
8883,75,Sweden,Austria,19.4,0,Abdul Naser Baluch,Stockholm,"Botkyrka Cricket Center, Stockholm"

In [55]:
pickle.dump(output,open('dataset_level2.pkl','wb'))

In [56]:
output[output['city'].isnull()]['venue'].value_counts()

Series([], Name: count, dtype: int64)

In [57]:
# If the given above is not empty then we'll run this
# x = np.where(output['city'].isnull(), output['venue'].str.split().apply(lambda x:x[0]), output['city'])

In [59]:
# output.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [60]:
total_df = output.groupby('match_id').sum()['runs'].reset_index()
output = output.merge(total_df,on='match_id')

In [61]:
output

,match_id,batting_team,bowling_team,ball,runs_x,player_dismissed,city,venue,runs_y
0,2,West Indies,New Zealand,0.1,0,0,Nelson,"Saxton Oval, Nelson",38
1,2,West Indies,New Zealand,0.2,0,0,Nelson,"Saxton Oval, Nelson",38
2,2,West Indies,New Zealand,0.3,1,0,Nelson,"Saxton Oval, Nelson",38
3,2,West Indies,New Zealand,0.4,1,0,Nelson,"Saxton Oval, Nelson",38
4,2,West Indies,New Zealand,0.5,0,0,Nelson,"Saxton Oval, Nelson",38
...,...,...,...,...,...,...,...,...,...
8879,75,Sweden,Austria,18.6,1,0,Stockholm,"Botkyrka Cricket Center, Stockholm",136
8880,75,Sweden,Austria,19.1,0,0,Stockholm,"Botkyrka Cricket Center, Stockholm",136
8881,75,Sweden,Austria,19.2,6,0,Stockholm,"Botkyrka Cricket Center, Stockholm",136
8882,75,Sweden,Austria,19.3,0,0,Stockholm,"Botkyrka Cricket Center, Stockholm",136
8883,75,Sweden,Austria,19.4,0,Abdul Naser Baluch,Stockholm,"Botkyrka Cricket Center, Stockholm",136

In [63]:
output['runs_x'] = pd.to_numeric(output['runs_x'])

output['current_score'] = (
    output
    .groupby('match_id')['runs_x']
    .cumsum()
)

In [64]:
output['over'] = output['ball'].apply(lambda x:str(x).split(".")[0])
output['ball_no'] = output['ball'].apply(lambda x:str(x).split(".")[1])

In [65]:
output['balls_bowled'] = (output['over'].astype('int')*6) + output['ball_no'].astype('int')

In [66]:
output['crr'] = round((output['current_score']*6)/output['balls_bowled'],2)

In [69]:
output['player_dismissed'] = output['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
output['player_dismissed'] = output['player_dismissed'].astype('int')
output['player_dismissed'] = pd.to_numeric(output['player_dismissed'])
output['player_dismissed'] = output.groupby('match_id')['player_dismissed'].cumsum()
output['wickets_left'] = 10 - output['player_dismissed']

In [70]:
final_df = output[['match_id','batting_team','bowling_team','runs_x','current_score','balls_bowled','wickets_left','crr','city','runs_y']]

In [71]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,balls_bowled,wickets_left,crr,city,runs_y
0,2,West Indies,New Zealand,0,0,1,9,0.00,Nelson,38
1,2,West Indies,New Zealand,0,0,2,8,0.00,Nelson,38
2,2,West Indies,New Zealand,1,1,3,7,2.00,Nelson,38
3,2,West Indies,New Zealand,1,2,4,6,3.00,Nelson,38
4,2,West Indies,New Zealand,0,2,5,5,2.40,Nelson,38
...,...,...,...,...,...,...,...,...,...,...
8879,75,Sweden,Austria,1,130,114,-115,6.84,Stockholm,136
8880,75,Sweden,Austria,0,130,115,-116,6.78,Stockholm,136
8881,75,Sweden,Austria,6,136,116,-117,7.03,Stockholm,136
8882,75,Sweden,Austria,0,136,117,-118,6.97,Stockholm,136
8883,75,Sweden,Austria,0,136,118,-119,6.92,Stockholm,136

In [86]:
final_df = final_df.sample(final_df.shape[0])

In [87]:
final_df['balls_left'] = 120 - final_df['balls_bowled']
final_df['balls_left'] = final_df['balls_left'].apply(lambda x:0 if x<0 else x)

KeyError: 'balls_bowled'

In [88]:
final_df['crr'] = round((final_df['current_score']*6)/final_df['balls_bowled'],2)

KeyError: 'balls_bowled'

In [89]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,wickets_left,crr,city,runs_y,balls_left,last_30_runs,last_five
8714,74,Austria,Romania,2,90,-57,9.15,Szodliget,182,61,51.0,46.0
335,5,Bangladesh,Pakistan,0,51,-50,5.28,Dhaka,133,62,32.0,NaN
1166,12,Bahrain,Germany,0,49,-20,10.14,Blantyre,207,91,NaN,39.0
7476,64,Malawi,Bahrain,1,69,-58,6.37,Kigali City,113,55,NaN,NaN
5307,47,Qatar,Saudi Arabia,4,4,6,6.00,Doha,177,116,39.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3437,30,Malaysia,Singapore,0,181,-91,11.08,Singapore,209,22,45.0,33.0
1998,19,Germany,Malawi,4,90,-25,16.36,Blantyre,219,87,59.0,30.0
3386,30,Malaysia,Singapore,4,68,-40,8.68,Singapore,209,73,56.0,25.0
3719,33,Hong Kong,Malaysia,0,15,2,11.25,Singapore,52,112,NaN,49.0
1766,17,Malawi,Bahrain,1,8,0,4.80,Blantyre,72,110,12.0,29.0

In [90]:
final_df.drop(columns=['balls_bowled'],inplace=True)

KeyError: "['balls_bowled'] not found in axis"

In [91]:
groups = final_df.groupby('match_id')

In [92]:
match_ids = final_df['match_id'].unique()
last_five = []

for id in match_ids:
    temp = groups.get_group(id)

    rolling_sum = temp['runs_x'].rolling(window=30).sum()

    last_five.extend(rolling_sum.tolist())

In [93]:
final_df['last_five'] = last_five

In [94]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,wickets_left,crr,city,runs_y,balls_left,last_30_runs,last_five
8714,74,Austria,Romania,2,90,-57,9.15,Szodliget,182,61,51.0,NaN
335,5,Bangladesh,Pakistan,0,51,-50,5.28,Dhaka,133,62,32.0,NaN
1166,12,Bahrain,Germany,0,49,-20,10.14,Blantyre,207,91,NaN,NaN
7476,64,Malawi,Bahrain,1,69,-58,6.37,Kigali City,113,55,NaN,NaN
5307,47,Qatar,Saudi Arabia,4,4,6,6.00,Doha,177,116,39.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3437,30,Malaysia,Singapore,0,181,-91,11.08,Singapore,209,22,45.0,NaN
1998,19,Germany,Malawi,4,90,-25,16.36,Blantyre,219,87,59.0,NaN
3386,30,Malaysia,Singapore,4,68,-40,8.68,Singapore,209,73,56.0,NaN
3719,33,Hong Kong,Malaysia,0,15,2,11.25,Singapore,52,112,NaN,NaN
1766,17,Malawi,Bahrain,1,8,0,4.80,Blantyre,72,110,12.0,52.0

In [95]:
final_df.dropna(inplace=True)

In [96]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,wickets_left,crr,city,runs_y,balls_left,last_30_runs,last_five
1067,11,Malawi,Germany,1,64,-46,7.25,Blantyre,144,67,31.0,44.0
3708,32,Hong Kong,Singapore,1,187,-113,9.35,Singapore,193,0,58.0,42.0
7407,63,Bahrain,Rwanda,1,163,-117,8.15,Kigali City,163,0,33.0,47.0
952,10,Bahrain,Tanzania,1,94,-57,8.81,Blantyre,209,56,38.0,52.0
2430,22,Singapore,Samoa,2,100,-90,6.32,Singapore,136,25,32.0,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4023,36,Kenya,United Arab Emirates,1,27,-21,5.40,Entebbe,98,90,24.0,19.0
6457,56,Malawi,Rwanda,2,46,-39,5.75,Kigali City,113,72,31.0,19.0
5660,50,Estonia,Finland,0,17,0,10.20,Tallinn,141,110,29.0,20.0
8181,70,Romania,Luxembourg,0,44,-32,7.14,Szodliget,178,83,43.0,22.0
1766,17,Malawi,Bahrain,1,8,0,4.80,Blantyre,72,110,12.0,52.0

In [97]:
eligible_cities = final_df['city'].value_counts()[final_df['city'].value_counts() > 600].index.tolist()
final_df = final_df[final_df['city'].isin(eligible_cities)]

In [98]:
X = final_df.drop(columns=['match_id','runs_x','runs_y'])
y = final_df['runs_y']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [99]:
X_test

,batting_team,bowling_team,current_score,wickets_left,crr,city,balls_left,last_30_runs,last_five
7416,Malawi,Bahrain,13,2,9.75,Kigali City,112,16.0,45.0
7162,Bahrain,Malawi,5,7,10.00,Kigali City,117,42.0,32.0
3041,Hong Kong,Malaysia,87,-66,7.15,Singapore,47,23.0,42.0
2562,Singapore,Malaysia,75,-95,4.50,Singapore,20,26.0,52.0
1254,Bahrain,Germany,194,-108,10.03,Blantyre,4,53.0,35.0
...,...,...,...,...,...,...,...,...,...
4429,Kenya,Uganda,61,-56,5.90,Entebbe,58,27.0,37.0
3880,Uganda,United Arab Emirates,12,-2,6.55,Entebbe,109,25.0,31.0
6794,Malawi,Rwanda,16,-1,8.73,Kigali City,109,26.0,37.0
3060,Hong Kong,Malaysia,109,-85,7.11,Singapore,28,41.0,34.0
4632,Uganda,Nigeria,66,-35,9.43,Entebbe,78,37.0,20.0

In [109]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\admin\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\admin\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\admin\anaconda3\lib\site-packages (from xgboost) (1.16.3)

In [111]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

In [112]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler()),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [113]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9401748776435852
4.540940284729004

In [114]:
pickle.dump(pipe,open('pipe.pkl','wb'))

In [122]:
common_teams = list(
    set(delivery_df['batting_team']) &
    set(delivery_df['bowling_team'])
)

common_teams

['Tanzania',
 'Samoa',
 'Singapore',
 'Nigeria',
 'Saudi Arabia',
 'Pakistan',
 'Malaysia',
 'Finland',
 'Hong Kong',
 'Rwanda',
 'Romania',
 'Sri Lanka',
 'Germany',
 'Zimbabwe',
 'Malawi',
 'Qatar',
 'Estonia',
 'Kenya',
 'Uganda',
 'Bangladesh',
 'Austria',
 'Bahrain',
 'United Arab Emirates']

In [123]:
eligible_cities

['Kigali City', 'Singapore', 'Blantyre', 'Entebbe']